### ISSUE TITLE
Command Failed Due to Signal: Segmentation Fault: 11

### ISSUE THREAD

**Issue by ryanbilak** [JosephGarcia/Firebase-Demo#1]
Hey! I've been trying to work through this same tutorial and have been running into the error above. I'm actually getting the same error when I compile and run your project as well. 

When compiling the Swift source files, in "Merge FriendlyChat.swiftmodule........"

I get a bunch of data back but at the bottom it shows:

1.	While loading members for 'SignInViewController' at <invalid loc>
2.	While deserializing 'setDisplayName' (FuncDecl #16) 

Did you run into this at all? I've been going crazy trying to get this to work.

**Comment by JosephGarcia** [comment]
Whats up Ryan!
Okay that error is a little tricky. I hit the Run command multiple times and it'll just disappear. Try to erase your derived data and just start building and running. The problem will go away. I am not sure why it pops up. But it seems to go away on its own after hitting run like 3-4 times. Let me know. I am on windows right now :P 

Technically its just there to bug you. I do not know why. Keep me posted

**Comment by ryanbilak** [comment]
Thanks Joe, I deleted the derived data and tried to build 5-6 times and no luck :(

**Comment by JosephGarcia** [comment]
No prob man :) It was bugging me out too. Currently I am not getting that error anymore. BUT I do see that error pop up when you open the regular xcodeproj. 

In other words MAKE SURE you're opening the xcworkspace file and NOT  the xcodeproj. 

Let me know :)

**Comment by ryanbilak** [comment]
Weirdest thing, I couldn't get it to work in your file and was having the same issue in another project I'm working on and all of a sudden it started working in my other project w/o that error. 

Idk what the deal is but it looks like it fixed itself for now.........

Thanks for trying to help though! Hopefully we'll see some new projects/tutorials on the new firebase over the next week or two

**Comment by JosephGarcia** [comment]
Ahh that sounds about right. I dont know why it does that. It's funny that cause I don't see an issue opened for that on the Friendlychat app for Firebase. Maybe within the next few days. You're welcome man. I am glad I could help :)

**Comment by JosephGarcia** [comment]
Find out what the problem was mate. You have to update your cocoapods :)

**Comment by ryanbilak** [comment]
Thanks Joseph, this worked for me, I can sleep at night again haha
